name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      # Deploy to Server 1
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS1 }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands on Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS1 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd home
            sudo mv * /var/www/html
      #Hostname IP DNS Private
      - name: Modify index.html for Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS1 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            PRIVATE_IP=$(hostname -I | awk '{print $1}')
            FILE_PATH="/home/index.html"
            if [ -f "$FILE_PATH" ]; then
              sudo sed -i "s/\$(hostname -f)/$PRIVATE_IP/" "$FILE_PATH"
              sudo mv "$FILE_PATH" /var/www/html/index.html
            else
              echo "Error: File $FILE_PATH not found."
              exit 1
            fi

      # Deploy to Server 2
      - name: Deploy to Server 2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS2 }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands on Server 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS2 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd home
            sudo mv * /var/www/html
      #Hostname IP DNS Private
      - name: Modify index.html for Server 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS2 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            PRIVATE_IP=$(hostname -I | awk '{print $1}')
            FILE_PATH="/home/index.html"
            if [ -f "$FILE_PATH" ]; then
              sudo sed -i "s/\$(hostname -f)/$PRIVATE_IP/" "$FILE_PATH"
              sudo mv "$FILE_PATH" /var/www/html/index.html
            else
              echo "Error: File $FILE_PATH not found."
              exit 1
            fi
